version: '3.7'

services:
  bot:
    build: .
    depends_on:
      - redis
    env_file: .env
  redis:
    image: redis
    volumes:
      - redis-data:/data
  db:
    image: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  redis-data:
  pg_data: